FROM alpine:latest

RUN apk update && apk add --no-cache \
  bash \
  mosquitto \
  mosquitto-clients \
  alpine-sdk \
  python \
  cmake \
  curl-dev \
  bsd-compat-headers \
  perl \
  jq \
  && rm -fr /tmp/*

RUN curl https://codeload.github.com/edenhill/kafkacat/tar.gz/master | tar xzf - && cd kafkacat-* && bash ./bootstrap.sh
RUN make -C /kafkacat-master bin-install

COPY mqtt2kafka.sh /
WORKDIR /
CMD /mqtt2kafka.sh
