FROM arm32v6/python:3-alpine

RUN apk --no-cache --update add mosquitto-clients

# Install flask (for the REST API server)
RUN pip install Flask

# Copy over the source
COPY watcher.py /
WORKDIR /

# Run the daemon
CMD python watcher.py
