FROM arm32v6/alpine:latest

RUN apk update \
    && apk add --no-cache bash mosquitto mosquitto-clients \
    && rm -fr /tmp/*

# Install kafkacat to publish msgs to IBM Public Cloud EventStreams (Kafka)
COPY keys/* /etc/apk/keys/
COPY kafkacat-*.apk /
RUN apk --no-cache add /kafkacat-*.apk && rm kafkacat-*.apk

COPY mqtt2kafka.sh /
WORKDIR /
CMD /mqtt2kafka.sh
